services:
  discord:
    build:
      context: .
      dockerfile: ScintillaVitae/Dockerfile
    container_name: discord
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
    networks:
      - main
    restart: unless-stopped

networks:
  main:
    driver: bridge